POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email":"Dorajet@gmail.com",
    "password":"Dorajet"
}


###

GET http://localhost:8080/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzI0NjY0MDg0LCJleHAiOjE3MjQ2Njc2ODR9.9wnhIVIIqzRI8CBu4tXnc2KCEtzM4J11wP_7MChne18

###


GET http://localhost:8080/orders/customer-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI0NjcxNTY5LCJleHAiOjE3MjQ2NzUxNjl9.zA9MTloX5ri0toIpvf4S2LaSXgmEnsEG5fHX6wYRcpM

